### ISSUE TITLE
GPU utilization decrease along the epochs

### ISSUE THREAD

**Issue by SHMCU** [Goldesel23/Temporal-Ensembling-for-Semi-Supervised-Learning#1]
I changed the code to make it run on my data. My images are also 32x32x3 patches. There are 18000+ labelled samples. I am using a GPU with 8GB memory. I set the batch size to 128. When training starts, everything looks good, the GPU utilization is about 50%, but as the training going on, the GPU utilization decreases slowly. After 100+ epoches, the training becomes very slow and the GPU utilization is about 1% to 5%. Does anyone have this problem? Thank you!

**Comment by SHMCU** [comment]
I did not see sess.run() in the code. It looks like every call to the class Model creates a new graph. Is that what the code is doing? Thank you!

**Comment by tensorfreitas** [comment]
Hi, I have not noticed that on my machine. There is no sess.run() because the code uses Eager execution, so there is no need for it!

**Comment by tensorfreitas** [comment]
I tested on another machine and I did not noticed the behavior you mentioned. The GPU usage varies depending on your batch size and it fluctuates during one epoch (and it can decrease when writing the logs to tensorboard logs), but the speed is constant on my tests. Are you sure is is not something related to the changes you made to run on your dataset?

**Comment by tensorfreitas** [comment]
After a recent push the problem was solved as described in #2 . I will close the issue.
