### ISSUE TITLE
Adapting for 1D data set. 

### ISSUE THREAD

**Issue by constant5** [Goldesel23/Temporal-Ensembling-for-Semi-Supervised-Learning#5]
How much effort would it be to convert this to handle row vectors instead of images?

**Comment by tensorfreitas** [comment]
I think the real effort would be for you to create a loader for your data (But in the end you would already would need to do it even if you didn't use this method). 

You would also need to adapt the network to be used on 1D data. 

Despite that I think this kind of loss can be minimized to any kind of network that you choose.

**Comment by constant5** [comment]
OK, I built my own loader!! Now I am trying to figure out how to build the network with a simple sequential model. Why did you define your own layer classes (Conv1D, and Dense) instead of simply importing the tf layers? I assume I only need dense and dropout layers for my tabular data.

**Comment by tensorfreitas** [comment]
I did not use tf.layers since I needed to apply the mean-only batch norm and weight normalization as described in the paper. But it should be easy to adapt it to Conv1D case if you also want mean-only batch norm and weight normalization

**Comment by constant5** [comment]
I'm not sure I need convolution layers because this is just a 1D data set.  It seems the NN should be able made of dense and drop out layers to create a good model.  

One question is how should I define simple layers for the pi_model.py starting on line 152:

"Set all the layers that need to be tracked in the process of gradients descent (pooling and dropout for example don't need to be stored)"

I am new to this super(PiModel, self).__init__().  Can you explain how this definition works?

**Comment by tensorfreitas** [comment]
`super(PiModel, self).init()` is needed because the model created is a derived class from `tf.keras.Model` and needs to be called in order for it to work properly. `super` is a built-in function in python. 

All the recommended documentation for eager execution uses it in defining the models as you can see here: https://www.tensorflow.org/guide/eager

**Comment by constant5** [comment]
OK so my next step is to adapt mean-only batch norm and weight normalization for the dense layers, right?

**Comment by tensorfreitas** [comment]
You don't need it since I already did that here: https://github.com/Goldesel23/Temporal-Ensembling-for-Semi-Supervised-Learning/blob/master/weight_norm_layers/Dense.py

**Comment by constant5** [comment]
So I just build them with calls to 

`self._dense = 
weight_norm_layers.Dense.Dense(units=10, activation=tf.nn.softmax,
                                                     kernel_initializer=tf.keras.initializers.he_uniform(),
                                                     bias_initializer=tf.keras.initializers.constant(                                          0.1),
                                                     weight_norm=True, mean_only_batch_norm=True)`

**Comment by tensorfreitas** [comment]
Exactly!

**Comment by constant5** [comment]
OK,  I am trying to define an input layer with:

`        self._input = weight_norm_layers.Dense.Dense(units=38, activation=tf.nn.softmax, 
                                                     kernel_initializer=tf.keras.initializers.he_uniform(),
                                                     bias_initializer=tf.keras.initializers.Constant(0.1),
                                                     weight_norm=True, mean_only_batch_norm=True)`

But I keep getting an error  `tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix [Op:MatMul] name: pi_model/dense/MatMul/`

My records are row vectors so with a batch size of 25 I get my tensor h size as (25, 1, 38).  Do I need to specify the input shape for the first layer?

**Comment by constant5** [comment]
I guess what we need is to define an input layer to the dense layers?

**Comment by tensorfreitas** [comment]
I guess you're not providing a compatible input? You don't need an input shape for it to work.

**Comment by constant5** [comment]
OK.  Well it seems I can pass my batch to the pi_model.py call function. I can print the input shape before and after noise as shown below:

`def call(self, input, training=True):
        """ Function that allows running a tensor through the pi model

        Arguments:
            input {[tensor]} -- batch of records
            training {bool} -- if true applies augmentation and additive noise

        Returns:
            [tensor] -- predictions
        """
        print('Before Noise: ', input.shape, input[1])

        if training:
            print('adding noise...')
            h = self.__additive_gaussian_noise(input, 0.15)
            #h = self.__apply_record_augmentation(h)
            print('After Noise', h.shape, h[1])
        else:
            h = input

        h = self._dense1(h, training)
        h = self._dense2(h, training)
        return self._dense3(h, training)`  

Before Noise:  (25, 1, 38) tf.Tensor(
[[-0.33647463  1.0157274  -0.33647463 -0.33647463 -0.19159584 -0.33647463
  -0.33647463 -0.33647463 -0.33647463 -0.33647463 -0.33647463 -0.33647463
  -0.33647463 -0.33647463 -0.33647463 -0.33647463 -0.33647463 -0.33647463
  -0.33647463  1.5952425   1.5952425  -0.33647463 -0.33647463 -0.33647463
  -0.33647463 -0.2881817  -0.33647463 -0.33647463  5.0723333   1.5952425
  -0.31908917 -0.3345429  -0.31908917 -0.33647463 -0.33647463 -0.33647463
  -0.33647463 -0.33647463]], shape=(1, 38), dtype=float32)
adding noise...
After Noise (25, 1, 38) tf.Tensor(
[[-0.09513949  0.97343045 -0.3066605  -0.12659216 -0.02343315 -0.33363065
  -0.4179578  -0.2887033  -0.33698046 -0.20555274  0.04663125 -0.4271093
  -0.45998678 -0.4740563  -0.4659654  -0.15212274 -0.5674074  -0.28883445
  -0.44090393  1.4797518   1.333977   -0.33901617  0.07568532 -0.3779075
  -0.2690576  -0.11005551 -0.4012068  -0.36593366  4.977174    1.6498508
  -0.30965862 -0.47616988 -0.34280834 -0.3113287  -0.5686118  -0.37310234
  -0.39282817 -0.23663768]], shape=(1, 38), dtype=float32)


But I get the matmul error when I get to the first dense layer and weight_norm=True.  I checked the size of the inputs to that matmul function and  A is (25, 1, 38) while B is (38, 1).  If I am reading this correctly A is my original tenor shape and B is should be random initialized tensor.  When B is initialized as self.V the shape is set to [input.shape[-1], units].   Is this the correct shape?

**Comment by tensorfreitas** [comment]
can you share your dense layers definitions? Without that I am not able to help much

**Comment by constant5** [comment]
Here you go:

        `self._dense1` = weight_norm_layers.Dense.Dense(input_shape=(1,38), units=1, activation=tf.nn.softmax, 
                                                     kernel_initializer=tf.keras.initializers.he_uniform(),
                                                     bias_initializer=tf.keras.initializers.Constant(0.1),
                                                     weight_norm=False, mean_only_batch_norm=True)
        self._dense2 = weight_norm_layers.Dense.Dense(units=38, activation=tf.nn.softmax, 
                                                     kernel_initializer=tf.keras.initializers.he_uniform(),
                                                     bias_initializer=tf.keras.initializers.Constant(0.1),
                                                     weight_norm=False, mean_only_batch_norm=True)
        self._dense3 = weight_norm_layers.Dense.Dense(units=2, activation=tf.nn.softmax, 
                                                     kernel_initializer=tf.keras.initializers.he_uniform(),
                                                     bias_initializer=tf.keras.initializers.Constant(0.1),
                                                     weight_norm=False, mean_only_batch_norm=True)    `

**Comment by tensorfreitas** [comment]
I don't think you should have that kind of architecture. 

First of all you have softmax in all layers as activation, second you have a network of 1 38 and 2 units, that does not make a lot of sense. I also think the error comes from the input_shape. It should be 38 and not 1 x 38.

**Comment by tensorfreitas** [comment]
I'm going to close this issue, but feel free to reopen if needed.
