### ISSUE TITLE
Result of supervised version with 1000 labels

### ISSUE THREAD

**Issue by zxlmufc** [Goldesel23/Temporal-Ensembling-for-Semi-Supervised-Learning#9]
Much appreciated for your succinct implementation. I'm trying to reproduce the result using your code. However, when I try to produce the baseline result, the supervised version with 1000 labels, using this code, it gives rather poor result, ~30%. Did you validate this by yourself? Or am I doing something stupid?
Thank you again.

**Comment by zxlmufc** [comment]
I've reproduced the supervised version of the model similar to the one in the paper

**Comment by iamshahd** [comment]
Hi,
I am also having trouble reproducing the original results. Could you share the fixes/edits you have made in order to reproduce the original results? Thanks.
